name: Subbus First Action
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: |
          echo "Hello World1"
          echo "Hello World2"
          echo "Hello World3"
      - name: print bye
        run: echo "Bye!"
